DROP TABLE T_RBW_AUDIO_VIDEO;
DROP TABLE T_RBW_CANDIDATO;
DROP TABLE T_RBW_CHATBOT;
DROP TABLE T_RBW_RECRUTADOR;
DROP TABLE T_RBW_VAGA;
DROP SEQUENCE SQ_RBW_VAGA;
DROP SEQUENCE SQ_RBW_RECRUTADOR;
DROP SEQUENCE SQ_RBW_CANDIDATO;
DROP SEQUENCE SQ_RBW_AUDIO_VIDEO;
DROP SEQUENCE SQ_RBW_CHATBOT;
DROP INDEX T_RBW_CAND_IDX;
DROP INDEX T_RBW_CAND_IDXV1;
DROP INDEX T_RBW_CAND_PK;
DROP INDEX T_RBW_VIDEO_PK;

