INSERT INTO
T_RBW_VAGA (NR_VAGA,NM_VAGA,DS_VAGA,VL_SALARIO)
values(SQ_RBW_VAGA.NEXTVAL,'Financeiro','Contabilidade',2500);

INSERT INTO
T_RBW_VAGA (NR_VAGA,NM_VAGA,DS_VAGA,VL_SALARIO)
values(SQ_RBW_VAGA.NEXTVAL,'Infraestrutura','Segurança de trafego',2500);

INSERT INTO
T_RBW_VAGA (NR_VAGA,NM_VAGA,DS_VAGA,VL_SALARIO)
values(SQ_RBW_VAGA.NEXTVAL,'RG','Gerente de RH',4000);


INSERT INTO
T_RBW_RECRUTADOR (CD_RECRUTADOR,NM_RECRUTADOR,DS_EMAIL,NM_SENHA)
VALUES(SQ_RBW_RECRUTADOR.NEXTVAL,'rodrigo','rodrigo@rodrigo.com','1234');
INSERT INTO
T_RBW_RECRUTADOR (CD_RECRUTADOR,NM_RECRUTADOR,DS_EMAIL,NM_SENHA)
VALUES(SQ_RBW_RECRUTADOR.NEXTVAL,'samanta','samanta@samanta.com','4321');

INSERT INTO
T_RBW_AUDIO_VIDEO (CD_AUDIO_VIDEO,FL_VIDEO ,FL_AUDIO)
VALUES(SQ_RBW_AUDIO_VIDEO.NEXTVAL,'http://techslides.com/demos/sample-videos/small.mp4',null);

	
INSERT INTO
T_RBW_CANDIDATO (CD_CANDIDATO,NR_CPF,NR_VAGA,CD_AUDIO_VIDEO,CD_CHATBOT,CD_RECRUTADOR,DT_NASCIMENTO,NR_MEDALHA,NM_CANDIDATO,DS_EMAIL,NM_SENHA)
VALUES (SQ_RBW_CANDIDATO.NEXTVAL,'1235678915',2,1,NULL,2,TO_DATE('1996-02-10','YYYY-MM-DD'),0,'Juliano','juliano.pereira@hotmail.com','12345');

INSERT INTO
T_RBW_CANDIDATO (CD_CANDIDATO,NR_CPF,NR_VAGA,CD_AUDIO_VIDEO,CD_CHATBOT,CD_RECRUTADOR,DT_NASCIMENTO,NR_MEDALHA,NM_CANDIDATO,DS_EMAIL,NM_SENHA)
VALUES (SQ_RBW_CANDIDATO.NEXTVAL,'49060761812',3,NULL,NULL,1,TO_DATE('1999-11-04','YYYY-MM-DD'),1,'Celso','lorensatto98@gmail.com','123456');

INSERT INTO
T_RBW_CANDIDATO (CD_CANDIDATO,NR_CPF,NR_VAGA,CD_AUDIO_VIDEO,CD_CHATBOT,CD_RECRUTADOR,DT_NASCIMENTO,NR_MEDALHA,NM_CANDIDATO,DS_EMAIL,NM_SENHA)
VALUES (SQ_RBW_CANDIDATO.NEXTVAL,'96583156840',1,NULL,NULL,1,TO_DATE('1969-08-14','YYYY-MM-DD'),2,'Cleise','negacleise@gmail.com','54321');

INSERT INTO
T_RBW_CANDIDATO (CD_CANDIDATO,NR_CPF,NR_VAGA,CD_AUDIO_VIDEO,CD_CHATBOT,CD_RECRUTADOR,DT_NASCIMENTO,NR_MEDALHA,NM_CANDIDATO,DS_EMAIL,NM_SENHA)
VALUES (SQ_RBW_CANDIDATO.NEXTVAL,'07532616851',1,NULL,NULL,2,TO_DATE('1966-09-01','YYYY-MM-DD'),0,'Celso','lorensattocls@gmail.com','55123');	

INSERT INTO
T_RBW_CANDIDATO (CD_CANDIDATO,NR_CPF,NR_VAGA,CD_AUDIO_VIDEO,CD_CHATBOT,CD_RECRUTADOR,DT_NASCIMENTO,NR_MEDALHA,NM_CANDIDATO,DS_EMAIL,NM_SENHA)
VALUES (SQ_RBW_CANDIDATO.NEXTVAL,'12345678912',2,NULL,NULL,2,TO_DATE('1996-01-24','YYYY-MM-DD'),1,'Camila','clorensatto.@gmail.com','111222');
